# Generated by Django 3.2.7 on 2021-09-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medicine name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish date')),
                ('aplication_time', models.TimeField(blank=True, null=True, verbose_name='Aplication time')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='animals.pet')),
            ],
            options={
                'unique_together': {('name', 'pet')},
            },
        ),
    ]
