# Generated by Django 3.2.7 on 2021-09-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('medicines', '0002_alter_medicine_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='animals.pet'),
        ),
    ]
