version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - .:/usr/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "8080:3000"
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge