version: "3.9"

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.postgres.env
    networks:
      - app-network

  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: tail -f /dev/null
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
      - pip_cache:/usr/local/lib/python3/site-packages
    env_file:
      - ./.postgres.env
      - ./.django.env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db_postgres_data:
  pip_cache:
