version: "3.9"

services:

  backend:
    build: .
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - ./src/:/usr/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - ./.env

  db:
    image: postgres:12.5
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - ./.env

volumes:
  node_modules:
  db_postgres_data:

networks:
  app-network:
    driver: bridge
