# Generated by Django 3.2.7 on 2021-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tricks',
            field=models.IntegerField(default=0),
        ),
    ]
