# Generated by Django 3.2.7 on 2021-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vaccine name')),
                ('application_date', models.DateField(verbose_name='Dose application date')),
                ('next_application_date', models.DateField(verbose_name='Next dose application date')),
            ],
        ),
    ]
