# Generated by Django 3.2.7 on 2021-09-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.pet'),
            preserve_default=False,
        ),
    ]
