# Generated by Django 3.2.7 on 2021-09-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('vaccines', '0002_auto_20210910_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='animals.pet'),
        ),
    ]
