# Generated by Django 3.2.7 on 2021-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_alter_vaccine_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='next_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next dose application date'),
        ),
    ]
