# Generated by Django 3.2.7 on 2021-09-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('vaccines', '0004_alter_vaccine_next_application_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('name', 'application_date', 'pet')},
        ),
    ]
