# Generated by Django 3.2.7 on 2021-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bath',
            name='location_bath',
            field=models.CharField(max_length=100, verbose_name='Location bath'),
        ),
    ]
